local_backend: true

# Decap still requires a backend block in local mode
backend:
  name: github
  repo: lyndon025/playtested
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "article"
    label: "Articles"
    folder: "src/content/article"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }

      - { label: "Author", name: "author", widget: "string", default: "lyndonguitar" }
      - { label: "Short Description", name: "description", widget: "text" }
      - { label: "Game", name: "game", widget: "string", required: false }

      # Category: dropdown (title-case to match existing files)
      - label: "Category"
        name: "category"
        widget: "select"
        options: ["Review", "Tech", "Write-up"]
        required: true

      # Tags: multi-select, at least 1, allow custom values
      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        options: ["PC", "Console", "Mobile"]
        allow_add: true
        required: true

      - { label: "Featured on Home", name: "featured", widget: "boolean", default: false, required: false }

      # Thumbnail: required image
      - { label: "Thumbnail", name: "thumb", widget: "image", required: true }

      # Gallery: OPTIONAL list of image paths (strings) — matches your MD exactly
      - label: "Gallery"
        name: "gallery"
        widget: "list"
        required: false

      - { label: "Score", name: "score", widget: "number", value_type: "float", min: 0, max: 10, step: 0.1, required: false }
      - { label: "Body", name: "body", widget: "markdown" }
