backend:
  name: github
  repo: lyndon025/playtested
  branch: main
  base_url: https://<YOUR_PAGES_DOMAIN>
  auth_endpoint: auth
  use_graphql: true

media_folder: "public/images/uploads"
public_folder: "/images/uploads"
publish_mode: editorial_workflow

collections:
  - name: "article"
    label: "Articles"
    folder: "src/content/article"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Lyndon Rebutoc" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Score", name: "score", widget: "number", value_type: "float", min: 0, max: 10, step: 0.1, required: false }
      - { label: "Thumbnail", name: "thumb", widget: "image", required: false }
      - { label: "Hero (Large)", name: "large", widget: "image", required: false }
      - label: "Gallery"
        name: "gallery"
        widget: "list"
        required: false
        field: { label: "Image", name: "image", widget: "image" }
      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false
      - { label: "Featured on Home", name: "featured", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }
